-- 3rd party plugins highlights
local lush = require("lush")
local base = require("aura.base")
local styles = require("aura.settings").styles

local plugins = lush(function()
	return {
		-- netrw
		netrwDir({ base.AuraPurpleFaded }),
		netrwClassify({ base.AuraPurpleFaded }),
		netrwLink({ base.AuraGray }),
		netrwSymLink({ base.AuraForeground }),
		netrwExe({ base.AuraOrange }),
		netrwComment({ base.AuraGray }),
		netrwList({ base.AuraBlue }),
		netrwHelpCmd({ base.AuraPurpleFaded }),
		netrwCmdSep({ base.AuraForeground }),
		netrwVersion({ base.AuraGreen }),
		-- nvim-treesitter
		TSNone({}),
		TSError({ base.Error }),
		TSTitle({ base.Title }),
		TSLiteral({ base.String }),
		TSURI({ base.Underlined }),
		TSVariable({ base.AuraForeground }),
		TSPunctDelimiter({ base.Delimiter }),
		TSPunctBracket({ base.Delimiter }),
		TSPunctSpecial({ base.Delimiter }),
		TSConstant({ base.Constant }),
		TSConstBuiltin({ base.Special }),
		TSConstMacro({ base.Define }),
		TSString({ base.String }),
		TSStringRegex({ base.String }),
		TSStringEscape({ base.SpecialChar }),
		TSCharacter({ base.Character }),
		TSNumber({ base.Number }),
		TSBoolean({ base.Boolean }),
		TSFloat({ base.Float }),
		TSFunction({ base.Function }),
		TSFuncBuiltin({ base.Special }),
		TSFuncMacro({ base.Macro }),
		TSParameter({ base.Identifier }),
		TSParameterReference({ TSParameter }),
		TSMethod({ base.Function }),
		TSField({ base.Identifier }),
		TSProperty({ base.Identifier }),
		TSConstructor({ base.Special }),
		TSAnnotation({ base.PreProc }),
		TSAttribute({ base.PreProc }),
		TSNamespace({ base.Include }),
		TSConditional({ base.Conditional }),
		TSRepeat({ base.Repeat }),
		TSLabel({ base.Label }),
		TSOperator({ base.Operator }),
		TSKeyword({ base.Keyword }),
		TSKeywordFunction({ base.Keyword }),
		TSKeywordOperator({ TSOperator }),
		TSException({ base.Exception }),
		TSType({ base.Type }),
		TSTypeBuiltin({ base.Type }),
		TSInclude({ base.Include }),
		TSVariableBuiltin({ base.Special }),
		TSText({ TSNone }),
		TSStrong({ gui = styles.bold }),
		TSEmphasis({ gui = styles.italic_strings }),
		TSUnderline({ gui = styles.underline }),
		TSComment({ base.Comment }),
		TSStructure({ base.AuraOrange }),
		TSTag({ base.AuraOrange }),
		TSTagDelimiter({ base.AuraGreen }),

		-- telescope.nvim
		TelescopeSelection({ base.AuraOrangeBold }),
		TelescopeSlectionCaret({ base.AuraRed }),
		TelescopeMultiSelection({ base.AuraGray }),
		TelescopeNormal({ base.AuraForeground }),
		TelescopeBorder({ TelescopeNormal }),
		TelescopePromptBorder({ TelescopeNormal }),
		TelescopeResultsBorder({ TelescopeNormal }),
		TelescopePreviewBorder({ TelescopeNormal }),
		TelescopeMatching({ base.AuraBlue }),
		TelescopePromptPrefix({ base.AuraRed }),
		TelescopePrompt({ TelescopeNormal }),
		-- lspsaga.nvim
		LspSagaDiagnosticBorder({ base.NormalNC }),
		LspSagaDiagnosticHeader({ base.AuraRed }),
		LspSagaDiagnosticTruncateLine({ base.NormalNC }),
		LspFloatWinBorder({ base.NormalNC }),
		LspSagaBorderTitle({ base.Title }),
		TargetWord({ base.Error }),
		ReferencesCount({ base.Title }),
		ReferencesIcon({ base.Special }),
		DefinitionCount({ base.Title }),
		TargetFileName({ base.Comment }),
		DefinitionIcon({ base.Special }),
		ProviderTruncateLine({ base.NormalNC }),
		SagaShadow({ base.AuraBg0 }),
		LspSagaFinderSelection({ base.Search }),
		DiagnosticTruncateLine({ base.NormalNC }),
		DiagnosticWarning({ base.DiagnosticWarn }),
		DiagnosticInformation({ base.DiagnosticInfo }),
		DefinitionPreviewTitle({ base.Title }),
		LspSagaShTruncateLine({ base.NormalNC }),
		LspSagaDocTruncateLine({ base.NormalNC }),
		LineDiagTuncateLine({ base.NormalNC }),
		LspSagaCodeActionTitle({ base.Title }),
		LspSagaCodeActionTruncateLine({ base.NormalNC }),
		LspSagaCodeActionContent({ base.Normal }),
		LspSagaRenamePromptPrefix({ base.AuraForeground }),
		LspSagaRenameBorder({ gui = styles.bold }),
		LspSagaHoverBorder({ gui = styles.bold }),
		LspSagaSignatureHelpBorder({ gui = styles.bold }),
		LspSagaCodeActionBorder({ gui = styles.bold }),
		LspSagaAutoPreview({}),
		LspSagaDefPreviewBorder({ gui = styles.bold }),
		LspLinesDiagBorder({ gui = styles.bold }),
		-- vim-startify
		StartifyBracket({ base.Delimiter }),
		StartifyFile({ base.Identifier }),
		StartifyNumber({ base.Number }),
		StartifyPath({ base.Directory }),
		StartifySlash({ base.Delimiter }),
		StartifySection({ base.Statement }),
		StartifySpecial({ base.Comment }),
		StartifyHeader({ base.Title }),
		StartifyFooter({ base.Title }),
		StartifyVar({ StartifyPath }),
		StartifySelect({ base.Title }),
		-- vim-signify
		SignifySignAdd({ base.AuraGreenSign }),
		SignifySignChange({ base.AuraPurpleFadedSign }),
		SignifySignDelete({ base.AuraRedSign }),
		-- syntastic
		SyntasticError({ base.AuraRedUnderline }),
		SyntasticWarning({ base.AuraOrangeUnderline }),
		SyntasticErrorSign({ base.AuraRedSign }),
		SyntasticWarningSign({ base.AuraOrangeSign }),
		-- termdebug
		debugPC({ bg = colors.faded_blue }),
		debugBreakpoint({ base.AuraRedSign }),
		-- vim-dirvish
		DirvishPathTail({ base.AuraPurpleFaded }),
		DirvishArg({ base.AuraOrange }),
		-- nerdtree
		NERDTreeDir({ base.AuraPurpleFaded }),
		NERDTreeDirSlash({ base.AuraPurpleFaded }),
		NERDTreeOpenable({ base.AuraOrange }),
		NERDTreeClosable({ base.AuraOrange }),
		NERDTreeFile({ base.AuraForeground }),
		NERDTreeExecFile({ base.AuraOrange }),
		NERDTreeUp({ base.AuraGray }),
		NERDTreeCWD({ base.AuraGreen }),
		NERDTreeHelp({ base.AuraForeground }),
		NERDTreeToggleOn({ base.AuraGreen }),
		NERDTreeToggleOff({ base.AuraRed }),
		-- coc.nvim
		CocErrorSign({ base.AuraRedSign }),
		CocWarningSign({ base.AuraOrangeSign }),
		CocInfoSign({ base.AuraBlueSign }),
		CocHintSign({ base.AuraPurpleFadedSign }),
		CocErrorFloat({ base.AuraRed }),
		CocWarningFloat({ base.AuraOrange }),
		CocInfoFloat({ base.AuraBlue }),
		CocHintFloat({ base.AuraPurpleFaded }),
		CocDiagnosticsError({ base.AuraRed }),
		CocDiagnosticsWarning({ base.AuraOrange }),
		CocDiagnosticsInfo({ base.AuraBlue }),
		CocDiagnosticsHint({ base.AuraPurpleFaded }),
		CocSelectedText({ base.AuraRed }),
		CocCodeLens({ base.AuraGray }),
		CocErrorHighlight({ base.AuraRedUnderline }),
		CocWarningHighlight({ base.AuraOrangeUnderline }),
		CocInfoHighlight({ base.AuraBlueUnderline }),
		CocHintHighlight({ base.AuraPurpleFadedUnderline }),
		-- ale.vim
		ALEError({ base.AuraRedUnderline }),
		ALEWarning({ base.AuraOrangeUnderline }),
		ALEInfo({ base.AuraBlueUnderline }),
		ALEErrorSign({ base.AuraRedSign }),
		ALEWarningSign({ base.AuraOrangeSign }),
		ALEInfoSign({ base.AuraBlueSign }),
		ALEVirtualTextError({ base.AuraRed }),
		ALEVirtualTextWarning({ base.AuraOrange }),
		ALEVirtualTextInfo({ base.AuraBlue }),
		-- vim-buftabline
		BufTabLineCurrent({ base.TabLineSel }),
		BufTabLineActive({ base.PmenuSel }),
		BufTabLineHidden({ base.TabLine }),
		BufTabLineFill({ base.TabLineFill }),
		BufTabLineModifiedCurrent({ BufTabLineCurrent }),
		BufTabLineModifiedActive({ BufTabLineActive }),
		BufTabLineModifiedHidden({ BufTabLineHidden }),
		-- ctrlP
		CtrlPMatch({ base.Identifier }),
		CtrlPNoEntries({ base.Error }),
		CtrlPPrtBase({ base.Comment }),
		CtrlPPrtCursor({ base.Constant }),
		CtrlPLinePre({ fg = base.AuraBackground.fg.hex }),
		CtrlPMode1({ base.Character }),
		CtrlPMode2({ base.LineNr }),
		CtrlPStats({ base.Function }),
		-- fzf.vim
		Fzf1({ fg = base.AuraBlue.fg.hex, bg = base.AuraBackground.fg.hex }),
		Fzf2({ fg = base.AuraOrange.fg.hex, bg = base.AuraBackground.fg.hex }),
		Fzf3({ fg = base.AuraForeground.fg.hex, bg = base.AuraBackground.fg.hex }),
		ShowMarksHLl({ base.AuraBlueSign }),
		ShowMarksHLu({ base.AuraBlueSign }),
		ShowMarksHLo({ base.AuraBlueSign }),
		ShowMarksHLm({ base.AuraBlueSign }),
		-- git-gutter
		GitGutterAdd({ base.AuraGreenSign }),
		GitGutterChange({ base.AuraPurpleFadedSign }),
		GitGutterDelete({ base.AuraRedSign }),
		GitGutterChangeDelete({ base.AuraPurpleFadedSign }),
		-- gitsigns.nvim
		GitSignsAdd({ base.AuraGreenSign }),
		GitSignsChange({ base.AuraPurpleFadedSign }),
		GitSignsDelete({ base.AuraRedSign }),
		GitSignsCurrentLineBlame({ base.NonText }),
		-- nvim-cmp
		CmpItemAbbr({ base.AuraForeground }),
		CmpItemAbbrDeprecated({ base.AuraForeground }),
		CmpItemAbbrMatch({ base.AuraBlue }),
		CmpItemAbbrMatchFuzzy({ base.AuraPurpleFaded }),
		CmpItemAbbrMatchFuzzy({ gui = styles.underline, fg = base.AuraBlue.fg.hex }),
		CmpItemKind({ base.AuraOrange }),
		CmpItemKindClass({ base.AuraGreen }),
		CmpItemKindConstructor({ base.AuraGreen }),
		CmpItemKindField({ base.AuraPurpleFaded }),
		CmpItemKindFile({ base.AuraOrange }),
		CmpItemKindFolder({ base.AuraOrange }),
		CmpItemKindFunction({ base.AuraPurple }),
		CmpItemKindInterface({ base.AuraGreen }),
		CmpItemKindKeyword({ base.Keyword }),
		CmpItemKindMethod({ base.AuraPurple }),
		CmpItemKindSnippet({ base.AuraOrange }),
		CmpItemKindText({ base.AuraForeground }),
		CmpItemKindValue({ base.AuraOrange }),
		CmpItemKindVariable({ base.AuraBlue }),
		CmpItemMenu({ base.AuraGray }),
		-- LSP
		LspCodeLens({ base.AuraGray }),
		LspReferenceRead({ bg = base.AuraBackground.fg.hex, gui = styles.underline }),
		LspReferenceText({ bg = base.AuraBackground.fg.hex, gui = styles.underline }),
		LspReferenceWrite({ bg = base.AuraBackground.fg.hex, gui = styles.underline }),
		-- NOTE: Deprecated settings (see https://github.com/neovim/neovim/pull/15585)
		LspDiagnosticsDefaultError({ base.AuraRed }),
		LspDiagnosticsSignError({ base.AuraRedSign }),
		LspDiagnosticsUnderlineError({ base.AuraRedUnderline }),
		LspDiagnosticsDefaultWarning({ base.AuraOrange }),
		LspDiagnosticsSignWarning({ base.AuraOrangeSign }),
		LspDiagnosticsUnderlineWarning({ base.AuraOrangeUnderline }),
		LspDiagnosticsDefaultInformation({ base.AuraBlue }),
		LspDiagnosticsSignInformation({ base.AuraBlueSign }),
		LspDiagnosticsUnderlineInformation({ base.AuraBlueUnderline }),
		LspDiagnosticsDefaultHint({ base.AuraPurpleFaded }),
		LspDiagnosticsSignHint({ base.AuraPurpleFadedSign }),
		LspDiagnosticsUnderlineHint({ base.AuraPurpleFadedUnderline }),
		LspDiagnosticsFloatingError({ base.AuraRed }),
		LspDiagnosticsFloatingWarning({ base.AuraOrange }),
		LspDiagnosticsFloatingInformation({ base.AuraBlue }),
		LspDiagnosticsFloatingHint({ base.AuraPurpleFaded }),
		LspDiagnosticsVirtualTextError({ base.AuraRed }),
		LspDiagnosticsVirtualTextWarning({ base.AuraOrange }),
		LspDiagnosticsVirtualTextInformation({ base.AuraBlue }),
		LspDiagnosticsVirtualTextHint({ base.AuraPurpleFaded }),
		-- Diagnostic
		DiagnosticError({ base.AuraRed }),
		DiagnosticSignError({ base.AuraRedSign }),
		DiagnosticUnderlineError({ base.AuraRedUnderline }),
		DiagnosticWarn({ base.AuraOrange }),
		DiagnosticSignWarn({ base.AuraOrangeSign }),
		DiagnosticUnderlineWarn({ base.AuraOrangeUnderline }),
		DiagnosticInfo({ base.AuraBlue }),
		DiagnosticSignInfo({ base.AuraBlueSign }),
		DiagnosticUnderlineInfo({ base.AuraBlueUnderline }),
		DiagnosticHint({ base.AuraPurpleFaded }),
		DiagnosticSignHint({ base.AuraPurpleFadedSign }),
		DiagnosticUnderlineHint({ base.AuraPurpleFadedUnderline }),
		DiagnosticFloatingError({ base.AuraRed }),
		DiagnosticFloatingWarn({ base.AuraOrange }),
		DiagnosticFloatingInfo({ base.AuraBlue }),
		DiagnosticFloatingHint({ base.AuraPurpleFaded }),
		DiagnosticVirtualTextError({ base.AuraRed }),
		DiagnosticVirtualTextWarn({ base.AuraOrange }),
		DiagnosticVirtualTextInfo({ base.AuraBlue }),
		DiagnosticVirtualTextHint({ base.AuraPurpleFaded }),
		-- mail.vim
		mailQuoted1({ base.AuraPurpleFaded }),
		mailQuoted2({ base.AuraPurple }),
		mailQuoted3({ base.AuraOrange }),
		mailQuoted4({ base.AuraGreen }),
		mailQuoted5({ base.AuraRed }),
		mailQuoted6({ base.AuraOrange }),
		mailSignature({ base.Comment }),
	}
end)

return plugins
